// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lhunsfvyegrjgejfgmwt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxodW5zZnZ5ZWdyamdlamZnbXd0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY4MjIyMzMsImV4cCI6MjA3MjM5ODIzM30.Z9ZvtkRx8yEOYKoRnNZ2SFf2RH57jv0lmPYZknZchBQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});